blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_details, name='post_details'),
    path('about/',views.About,name="about"),
    path('blog/about.html',views.About,name="about"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/blog/about',views.aboutWargs,name="AboutWargs"),

    path('blog/contact.html',views.Contact,name="contact"),
    path('contact/',views.Contact,name="contact"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/blog/contact',views.contactWargs,name="ContactWargs"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('blog/',include('blog.urls',namespace='blog')),
    path('about/',include('blog.urls',namespace='blog')),
    path('blog/about.html',include('blog.urls',namespace='blog')),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/blog/about',include('blog.urls',namespace='blog')),

    path('contact/',include('blog.urls',namespace='blog')),
    path('blog/contact.html',include('blog.urls',namespace='blog')),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/blog/contact',include('blog.urls',namespace='blog')),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    imageURL=models.CharField(max_length=500)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    # image=models.ImageField(upload_to="blog/images",default="")
    published = PublishedManager()

    # Meta data

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_details',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment	by	{}	on	{}'.format(self.name,	self.post)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
    

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Post
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from .forms import CommentForm
from django.urls import reverse

# Create your views here.


def post_list(request):
    posts = Post.published.all()
    params = {'posts': posts}
    return render(request, 'blog/post/list.html', params)


def post_details(request,	year,	month,	day,	post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    #	List	of	active	comments	for	this	post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        #	A	comment	was	posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #	Create	Comment	object	but	don't	save	to	database	yet
            new_comment = comment_form.save(commit=False)
            #	Assign	the	current	post	to	the	comment
            new_comment.post = post
            #	Save	the	comment	to	the	database
            new_comment.save()

    else:
        comment_form = CommentForm()
    return render(request,
                  'blog/post/details.html',
                  {'post':	post,
                   'comments':	comments,
                   'new_comment':	new_comment,
                   'comment_form':	comment_form})


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,  'posts': posts})


def About(request):
    return render(request, 'blog/about.html')


def Contact(request):
    return render(request, 'blog/contact.html')


def aboutWargs(request,year,month,day,post):
    return render(request, 'blog/about.html')


def contactWargs(request,year,month,day,post):
    return render(request, 'blog/contact.html')

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abouts</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap');

        body {
            padding-top: 10vh;
            background-color:rgb(248, 244, 241);
        }

        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Ubuntu', sans-serif;
            width: 80vw;
            height: 80vh;
            margin: auto;
            color: rgb(89, 86, 86);
        }

        h2 {
            font-size: 30px;

        }

        .contact-blocks {
            display: flex;
            height: 90%;
            color: rgb(75, 72, 72);
        }

        .outer-cover-cust {
            border: 1px solid bl;
        }

        .customer-care,
        .sales-marketing {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            margin: auto;
            height: 80%;
            border-radius: 25px;
        }


        .customer-care {
            width: 300px;
            border: 1px #4737d3 solid;
            margin: 25px;
            box-shadow: 0 -10px 5px #4737d3;
        }



        .sales-marketing {
            width: 300px;
            margin: 25px;
            border: 1px #55c397 solid;
            box-shadow: 0 -10px 5px #55c397;

        }

        .sales-marketing h3,
        .customer-care h3 {
            padding-top: 25px;
            text-align: center;
        }

        .sales-marketing p,
        .customer-care p {
            text-align: justify;
            margin-top: 40px;
            padding-bottom: 30px;
            text-align: center;
        }



        @media screen and (max-width:760px) {
            body {
                padding-top: 0;

            }

            .contact-blocks {
                flex-direction: column;
            }
        }

        .typeAnim {
            overflow: hidden;
            border-right: .15em light whitesmoke;
            white-space: nowrap;
            animation:
                typing 1.2s forwards;
            width: 0;
        }

        @keyframes typing {
            from {
                width: 0
            }

            to {
                width: 100%
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>About</h2>
        <div class="contact-blocks">
            <div class="customer-care">
                <h3 class="typeAnim">Hello friends, My name is Shahzad!!</h3>
                <p>I am passionate about learning and trying new technologies.</p>
            </div>

            <div class="sales-marketing">
                <p style="margin-top:120px ;">This project work is done during my internship at <b>Suven Consultants and
                        Technology Pvt. Ltd</b> under the guidance of the best industry experts.
                    It is based on the <b>Django </b>framework of python. The front-end is based on <b>HTML </b>and
                    <b>CSS.</b>
                </p>
            </div>

        </div>
    </div>
</body>

</html>

<!--
.typeAnim {
    overflow: hidden;
    border-right: .15em light whitesmoke;
    white-space: nowrap;
    animation:
        typing 1.2s forwards;
    width: 0;
}

@keyframes typing {
    from {
        width: 0
    }

    to {
        width: 100%
    }
}

@keyframes glowing {
    0% {
      background-color: #464949;
      box-shadow: 0 0 3px #6a6d69;
    }
    50% {
      background-color: #979997;
      box-shadow: 0 0 10px #9c9c9c;
    }
    100% {
      background-color: #caccc9;
      box-shadow: 0 0 3px #f0f7ee;
    }
  }
  .btn {
    animation: glowing 2500ms infinite;
  }
  -->

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Spectral:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&family=Spectral:wght@200&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            font-weight: bold;
            font-family: 'Spectral', serif;
            background-color:rgb(248, 244, 241);

        }
        h1{
            margin-top: 0;
            font-family: 'Courgette', cursive;
        }

        .navbar {
            margin-top: -8px;
            padding: 1px;
        }

        .navbar li {
            float: left;
            list-style: none;
            margin: 5px 7px;

        }

        .navbar li a:hover {
            background: rgb(219, 181, 154);

        }

        .navbar ul {
            padding-left: 530px;
            overflow: auto;
            position: relative;
        }

        .navbar li a {
            font-family: "calibri";
            text-decoration: none;
            border-radius: 5px;
            color: black;
            padding: 5px;
            margin: 5px;
        }
        .secondary-header{
            background-color: rgb(219, 181, 154);
        }

        .footer {
            background-color: rgb(219, 181, 154);
            margin-top: 32px;
            color: rgb(48, 46, 46);
            text-align: center;
            font-family: Calibri;
            font-weight: bold;
            padding: 17px;
        }

        .footer p {
            margin: auto;
        }

        .card-title:hover {

            color: rgb(219, 181, 154);
        }

        .card-title  {
            text-align: justify;
            font-size: 28px;
            font-weight: bold;
            font-family: 'Segoe UI Black';
            color: black;
            margin-top: 4px;
        }
        .btn,
        .btn-primary {
            text-decoration: none;
            background-color: rgb(219, 181, 154);
            color: whitesmoke;
            padding: 8px 36px;
            border-radius: 12px;
        }

        .btn:hover {
            background: #f66b5d;
        }

        .addcom {
            color: black;
            background-color: rgb(219, 181, 154);
            padding: 3px;
            border-radius: 4px;
        }

        .addcom:hover {
            background: #f66b5d;
        }
        .detailImg{
            margin-top: 10px;
        }
        #id_name, #id_email{
            padding: 6px;
            background-color:#d9f7de;
            margin-top: 15px;
            border:2px solid slategrey;
        }
        #id_body{
            background-color:rgb(230, 236, 219);
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar">
            <ul>
                <li>
                    <script>
                        document.write('<a href="' + document.referrer + '">Home</a>');
                    </script>
                    <!-- <a href='post/list'>Home</a></li> -->
                <li><a href='blog/about'>About</a></li>
                <li><a href="blog/contact">Contact us</a></li>
            </ul>

        </nav>
    </header>
    <div class="secondary-header">
            <h1 style="color: rgb(48, 46, 46);font-size:23px;font-family:Calibri;margin-right:26px;padding: 25px ;text-align: center;">Smart Blogger</h1>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="footer">
            <p>www.smartblogger.com</p>
            <p>All rights reserved &copy; 2022</p>
        </div>
    </footer>

</body>

</html>

blog/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap');
        body {
            background-color:rgb(248, 244, 241);
            padding-top: 10vh;
        }
        
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Ubuntu', sans-serif;
            width: 80vw;
            height: 80vh;
            margin: auto;
            color: rgb(89, 86, 86);
        }
        h2{
            font-size: 30px;
   
        }
        hr{
            width: 70%;
        }
        h4{
            font-size: 20px;
        }
        .contact-blocks {
            display: flex;
            height: 90%;
            color: rgb(75, 72, 72);
        }
        
        .outer-cover-cust {
            border: 1px solid bl;
        }
        
        .customer-care{
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            margin: auto;
            height: 80%;
            border-radius: 25px;
        }
        

        .customer-care {
            width: 300px;
            border: 1px #4737d3 solid;
            margin: 25px;
            box-shadow: 0 -10px 5px #4737d3;
        }
        
        .customer-care h3 {
            padding-top: 25px;
            text-align: center;
        }
        
        .customer-care p {
            padding-bottom: 40px;
            text-align: center;
           margin-top: 60px;
          font-weight: bold;
          color: #1734c3;

        }
        
        button {
            font-size: 15px;
            border-radius: 25px;
            padding: 10px 35px;
            border: 0;
            margin: 5px;
        }
        
        .customer-care button{
            background: #4737d3 ;
            color: rgb(232, 228, 228);
        }
                
        .customer-care button:hover{
            color: rgb(139, 134, 134);
        }
                
        .customer-care a {
            padding-top: 20px;
            text-decoration: none;
            font-weight:900;
            color: #4737d3;
        }
        .customer-care a:hover { 
            color: #7972b5; 
        }
        @media screen and (max-width:760px) {
            body{
                padding-top: 0;

            }
            .contact-blocks{
                flex-direction: column;
            }
        }
        .typeAnim {
            overflow: hidden;
            border-right: .15em light whitesmoke;
            white-space: nowrap;
            animation:
                typing 1.2s forwards;
            width: 0;
        }

        @keyframes typing {
            from {
                width: 0
            }

            to {
                width: 100%
            }
        }
    </style>
</head>

<body>
    <div class="container typeAnim">
        <h2>Contact Us</h2>
        <hr>
        <h4>Have any suggestions? I'd love to hear from you</h4>
        <div class="contact-blocks">
            <div class="customer-care">
                <h3>Email</h3>
                <p>shahzadsayyed1729@gmail.com</p>
            </div>

        </div>
    </div>
</body>

</html>

blog/templates/blog/pagination.html
<style>
 .step-links a{
        text-decoration: none;
        background-color: rgb(219, 181, 154);
        color: white;
        padding: 5px 13px;
    border-radius: 9px;
    margin: 5px;
 }   
 .pagination{
    margin:61px 38px 46px 592px;
 }
 .step-links a:hover{
    background: #f66b5d;
 }
</style>
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{	page.previous_page_number	}}">Previous</a>
        {% endif %}
        <span class="current">
            Page <b>{{ page.number }}</b> of <b>{{ page.paginator.num_pages }}</b>
        </span>
        {% if page.has_next %}
        <a href="?page={{	page.next_page_number	}}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/details.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
{% load static %}
<div style="border-radius: 2px 70px 70px 2px;">
<div class="detailImg">
<img src="{{post.imageURL}}" width="400" height="305" alt="...">
</div>
<h1 style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin:18px;margin-left:415px;margin-top: -250px;">{{ post.title }}</h1>
<p class="date" style="margin-top:-16px;font-style:italic;margin-bottom: 96px; margin:18px;margin-left:415px;margin-bottom: 200px">
	Published {{ post.publish }} by {{ post.author }}
</p> <!-- Main Para-->
<div style="font-size: 19px;text-align: justify; margin:18px;margin-bottom: 80px; margin-top: 80px;">
	{{ post.body|linebreaks }}
</div>

<div class="comment-section">
	<!-- Comment Section-->
	{% with comments.count as total_comments %}
	<h2
		style="margin-bottom:33px;font-size: 32px;font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
		{{ total_comments }} comment{{ total_comments|pluralize }}
	</h2>
	{% endwith %}

	{% for comment in comments %}
	<div class="comment"
		style=" margin:5px;display: block; width: 35%;border-radius: 4px;padding: 8px; background-color: rgb(147 255 186);">
		<p class="info" style="color: rgb(72 72 72); font-weight: bold; margin-top: 15px;">
			Comment {{ forloop.counter }} by {{ comment.name }}
			{{ comment.created }}
		</p>
		{{ comment.body|linebreaks }}
	</div>
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form name="form1" action="." method="post" autocomplete="off">
	{{ comment_form.as_p }}
	{% csrf_token %}
	<p><input class="addcom" type="submit" value="Add Comment"></p>
</form>

{% endif %}
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Smart Blogger{% endblock %}
{% block content %}
{% load static %}
<div class="main-body" style="display: block;">
  {% for post in posts %}

  <div class="card" style="margin-top: 38px;width: 80%;height: 300px;position: relative;left:120px;">

    <div class="card-body" style=" border-radius: 30px;background-color: rgb(241, 238, 235); padding: 20px 30px;">
      <img src='{{post.imageURL}}' width="350px" height="250px" alt="No Image">
      <div style="margin-left:417px;display: block;margin-top: -260px;">
          <h5 class="card-title">{{ post.title}}</h5>
        <p class="date" style="font-style: italic; font-size:14px; margin-top: -42px;margin-bottom: 60px;">Published {{ post.publish }} by {{ post.author }}</p>
        <p class="card-text" style="background-color: darkgrey; margin-top: 36px;">{{post.body|truncatewords:20|linebreaks }}</p>
        <a href="{{	post.get_absolute_url	}}" class="btn btn-primary">Read</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% include "blog/pagination.html" with page=posts %}

{% endblock %}

<!-- <img src='/static/media/{{post.image}}' -->